import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";

// const geistSans = Noto_Sans({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

const notoSans = Noto_Sans({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${notoSans} ${notoSans} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <div className="h-screen bg-[#F8FAFC] text-slate-700">{children}</div>
      </body>
    </html>
  );
}
